feat: add authentication endpoints
tazkrtak/server pull request #17
Opened 2021-04-27 17:25 UTC by MonicaTanios

* create database structure migration
 * add register service/endpoint
 * add login service/endpoint
 * create register/login dto

Co-authored-by: Micheline Medhat <michelinemedhat@gmail.com>

2021-04-27 18:00 UTC, YoussefRaafatNasry requested changes
@MichaelSafwatHanna, please review the DTO's validation part _(using prisma as we discussed before)_. You can check the comments too because I am not fully aware of the server project.

2021-04-27 18:00 UTC, yousinix commented on .gitignore
> +/prisma/migrations
Migrations should be checked in source control

2021-04-27 18:00 UTC, yousinix commented on package.json
> +    "db:migrate": "prisma migrate dev --name init"
Don't add `--name ...`

2021-04-27 18:00 UTC, yousinix commented on package.json
> +    "db:push": "prisma db push --preview-feature --accept-data-loss",
Replace this script by one that pushes migrations to db

2021-04-27 18:00 UTC, yousinix commented on prisma/schema.prisma
> +  secret        String
`seed` and `secret` are the same thing as far as I can understand, aren't they?

2021-04-27 18:00 UTC, yousinix commented on src/users/users.service.ts
> +    }
Don't throw exception, just return the `user` which would be `null` if not found.

2021-04-27 18:00 UTC, yousinix commented on src/users/users.service.ts
> +  async register(registerUserDto: RegisterUserDto): Promise<User> {
This should be create as it was, the register/login logic should be handled in the controller.

2021-04-27 18:00 UTC, yousinix commented on src/users/users.service.ts
> +        );
The thrown exception should have the following properties:

- Status code: [`409`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409)
- `validationErrors` property 

See [`ValidationException`](https://github.com/tazkrtak/server/blob/master/src/infrastructure/validation-exception.ts), I suggest creating another exception called `NonUniqueException` with the above properties.

2021-04-27 18:00 UTC, yousinix commented on src/users/users.controller.ts
> +import { User } from './interfaces/user.interface';
Rename the `User` to `UserDto` because it will conflict with prisma's types.

2021-04-27 19:38 UTC, YoussefRaafatNasry requested changes

2021-04-27 19:38 UTC, YoussefRaafatNasry commented on src/users/dto/register-user.dto.ts
> +  credit: number;
`credit` is not sent in DTO, it defaults to zero in the prisma schema already.

2021-04-27 19:38 UTC, YoussefRaafatNasry commented on src/users/interfaces/user.interface.ts
> -  key: string;
The `key` is sent back in this DTO, shouldn't be removed.

2021-04-27 19:38 UTC, YoussefRaafatNasry commented on src/users/interfaces/user.interface.ts
> +export interface UserDto {
Rename this file using DTO convention

2021-04-27 19:38 UTC, YoussefRaafatNasry commented on src/users/users.service.ts
> +      throw new NotFoundException('Incorrect user id or password.');
Should be `UnauthorizedException` (status code 401).

2021-04-27 19:38 UTC, YoussefRaafatNasry commented on src/users/users.service.ts
> +      throw new NonUniqueException(err);
We should specify which field(s) are violating the uniqueness constraints using `IFieldValidationError`.

2021-04-27 19:38 UTC, YoussefRaafatNasry commented on src/users/users.service.ts
> +          ...registerUserDto,
Passwords should be hashed.

2021-04-27 19:48 UTC, YoussefRaafatNasry requested changes

2021-04-27 19:48 UTC, YoussefRaafatNasry commented on src/users/users.controller.ts
>    })
We should specify all other paths/status codes too.

2021-04-28 15:35 UTC, MichaelSafwatHanna commented on package.json
> +    "js-sha512": "^0.8.0",
we have `[crypto-js](https://github.com/brix/crypto-js)` in our dependencies, I checked their docs and they have hashing algorithms (including sha512), can you investigate using it? to minimize our dependency tree.

2021-04-30 17:40 UTC, YoussefRaafatNasry approved these changes, later dismissed

2021-04-30 17:51 UTC, YoussefRaafatNasry approved these changes

2021-04-30 17:51 UTC, merged